### ISSUE TITLE
Drops can only be played once...ish

### ISSUE THREAD

**Issue by spikeheap** [omgmog/sound-dropper#10]
Once you've played a drop, it won't play again until you play something else or refresh the page.

## Steps to reproduce

1. Visit https://sound.me.uk/
2. Click play on a drop
3. Either wait for the clip to finish or click stop (both have the same behaviour)
4. Click play

## Expected

The clip plays again

## Actual

no-op

https://user-images.githubusercontent.com/464482/121690081-4c242900-cabd-11eb-90ec-22c2be075697.mov

**Comment by omgmog** [comment]
Fixed in a71bf67 :100:
